apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: cd-tools
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "50"
spec:
  project: tools
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: 1.11.0
    helm:
      releaseName: abhra
      values: |-
          installCRDs: false
          podDnsPolicy: "None"
          podDnsConfig:
            nameservers:
              - "1.1.1.1"
              - "8.8.8.8"
  destination:
    namespace: cluster-tools
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true

