apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-kaniko
  namespace: cd-tools
  annotations:
    argocd.argoproj.io/sync-wave: "300"
spec:
  templates:
    - name: kaniko-build-template
      volumes:
        - name: kaniko-secret
          secret:
            secretName: registry-secret
            items:
              - key: .dockerconfigjson
                path: config.json
      inputs:
        parameters:
          - name: project
      container:
        image: gcr.io/kaniko-project/executor:debug
        command: [/bin/sh]
        args: 
          - "-c"
          - >-
            /kaniko/executor
            {{workflow.parameters.gitlabcontext}} 
            --context-sub-path=src/{{inputs.parameters.project}}
            --dockerfile=Dockerfile 
            --verbosity=debug
            --destination=rg.fr-par.scw.cloud/guru/{{inputs.parameters.project}}:{{workflow.parameters.commitId}} 
        volumeMounts:
          - name: kaniko-secret
            mountPath: /kaniko/.docker/
        env:
          - name: GIT_USERNAME 
            valueFrom:
              secretKeyRef:
                name: gitlab-guru
                key: username
          - name: GIT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: gitlab-guru
                key: token
    - name: filter-git-projects-template
      inputs:
          parameters:
            - name: filter-prefix
      script:
        image: python:alpine3.6
        command: [python]
        source: |
          import json, sys

          projects = []

          for commit in {{workflow.parameters.commits}}:
            for key in ["added", "modified", "removed"]:
              for line in commit.get(key):
                if line.startswith("{{inputs.parameters.filter-prefix}}/"):
                  projects.append(line.split("/", 2)[1])

          projects = list(dict.fromkeys(projects))
          json.dump(projects, sys.stdout)
    - name: helm-package-template
      inputs:
          parameters:
            - name: project
      container:
        image: alpine/helm
        command: [/bin/sh]
        args: 
          - "-c"
          - >-
            apk add curl && 
            git clone {{workflow.parameters.gitlaburl}} &&
            helm package guru/charts/{{inputs.parameters.project}} &&
            TGZ_FILE=$(helm package guru/charts/{{inputs.parameters.project}} | cut -d ":" -f 2 | tr -d " ") &&
            curl --request POST --form 'chart=@'$TGZ_FILE'' --user $GIT_USERNAME:$GIT_PASSWORD https://gitlab.com/api/v4/projects/abhra-shambhala%2Fguru/packages/helm/api/stable/charts
        env:
          - name: GIT_USERNAME 
            valueFrom:
              secretKeyRef:
                name: gitlab-guru
                key: username
          - name: GIT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: gitlab-guru
                key: token


          
      
