
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: defectdojo-as
  namespace: cd-tools
spec:
  generators:
  - clusters: {}
  template:
    metadata:
      name: defectdojo
    spec:
      project: tools
      source:
        chart: defectdojo
        repoURL: https://raw.githubusercontent.com/DefectDojo/django-DefectDojo/helm-charts
        targetRevision: 1.6.59
        helm:
          # Postgresql overlapping
          releaseName: abhra
          values: |
            createSecret: true
            createRabbitMqSecret: true
            createRedisSecret: true

            database: redis

            redis:
              enabled: true

            extraConfigs:
              DD_SOCIAL_AUTH_GOOGLE_OAUTH2_ENABLED: 'true'
              DD_SOCIAL_AUTH_GOOGLE_OAUTH2_WHITELISTED_DOMAINS: 'wescale.fr'
              DD_MEDIA_ROOT: '/app/media'
            
            host: defectdojo.{{metadata.labels.abhra.shambhala/url-base-path}}
            
            django:
              ingress:
                enabled: true
                ingressClassName: nginx
                annotations:
                  cert-manager.io/cluster-issuer: 'letsencrypt-{{metadata.labels.abhra.shambhala/environment-type}}'
                  kubernetes.io/tls-acme: 'true'
                activateTLS: true
                secretName: defectdojo-tls
      destination:
        namespace: cluster-tools
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
        - CreateNamespace=true