apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dependency-track
  namespace: cd-tools
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: tools
  source:
    chart: dependency-track
    repoURL: https://evryfs.github.io/helm-charts
    targetRevision: 1.5.5
    helm:
      releaseName: abhra
      values: |
        ingress:
          enabled: true
          ingressClassName: nginx
          annotations:
            cert-manager.io/cluster-issuer: 'letsencrypt-{{metadata.labels.abhra.shambhala/environment-type}}'
            kubernetes.io/tls-acme: 'true'
          hosts: 
            - dependency.{{metadata.labels.abhra.shambhala/url-base-path}}
          path: /
          pathType: Prefix
          tls: 
            - secretName: dependency-track-cert
              hosts:
                - dependency.{{metadata.labels.abhra.shambhala/url-base-path}}
  destination:
    namespace: cluster-tools
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true

