apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: default
  namespace: tools-argo-events
spec:
  nats:
    native:
      replicas: 3 # optional, defaults to 3, and requires minimal 3
      auth: token # optional, default to none
      persistence: # optional
        storageClassName: standard
        accessMode: ReadWriteOnce
        volumeSize: 10Gi
